### ISSUE TITLE
need a hint on Timer reporting to Atlas

### ISSUE THREAD

**Issue by krutsko** [Netflix/spectator#239]
I found this wiki and example how to publish Gauge into Atlas. (and it's working fine)
https://github.com/Netflix/atlas/wiki/Getting-Started#running-demo-with-memory-storage

I have tried an example from https://github.com/Netflix/spectator/wiki/Timer-Usage , but has no luck with  `DefaultTimer`.

Could anybody share any hint / example on how to report Timer values to Atlas? 

Thanks

**Comment by brharrington** [comment]
Internally we do it by using the [servo registry](https://github.com/Netflix/spectator/wiki/Servo-Registry) and configuring [servo to publish to Atlas](https://github.com/Netflix/servo/tree/master/servo-atlas). This path was mostly chosen due to the history behind how these things evolved internally at Netflix. We have a ton of internal code using servo and need to maintain compatibility for that data. There are some additional details in the [servo comparison wiki](https://github.com/Netflix/spectator/wiki/Servo-Comparison).

Longer term, I have a local branch where I'm experimenting with a registry that provides an rxjava Observable for consumers. Then we would provide some subscribers that could publish to Atlas, CloudWatch, etc.

**Comment by krutsko** [comment]
Thank @brharrington for the links. I will investigate them deeper later on.

As I see, all values reported as scalar `long value`. 
And Timer (and DistributionSummary as well) values for reporting calculated on the client side. (I was thinking, that Atlas did calculation.)

**Comment by brharrington** [comment]
By calculated on the server side do you mean sending all values recorded by a timer to the server? The overhead of that makes it undesirable for many of our high volume use-cases. Where it is desirable internally there is typically other associated logging context information for the event that is needed and internally there is a separate data pipeline system used for that type of info with different tradeoffs. In many cases though both will be used, spectator meters will be updated based on the events to get a high level summary for operational monitoring and the raw events will go to the data pipeline for more fine grained analysis after a problem has been detected and isolated. 

For spectator, how values are reported will depend on the registry implementation used. The DefaultRegistry gets used a lot with [unit tests](https://github.com/Netflix/spectator/wiki/Testing) and keeps an overall count and in the case of timers and distribution summaries a total.

That said all values going into Atlas are doubles that summarize the behavior for a given step interval. If you have ever used rrdtool it is similar, only the metadata is a set of dimensions rather than a simple name. In the case of the ServoRegistry it will maintain local counts for a configured interval and then report the values. For counters it will be the average rate per second over the interval. Timers and distribution summaries are composites so it will report multiple time series per timer to summarize the behavior. I need to add some docs to the wiki on the values we report so we can get effective aggregates to make this a bit more clear to users. I'll try to get that done this weekend and update the ticket.

**Comment by pparth** [comment]
- Is the internal configurable?
- I cannot see whether there is support for quantiles calculation in this Timer implementation. Am i missing something?

**Comment by brharrington** [comment]
> Is the interval configurable?

Yes. I'll update the [readme](https://github.com/Netflix/servo/tree/master/servo-atlas) with some details about that.

> I cannot see whether there is support for quantiles calculation in this Timer implementation.

With Atlas there are typically two approaches to this right now:

* Locally computed percentiles, e.g. the servo StatsTimer. We are generally discouraging this now because we are typically looking at aggregates that we slice and dice across clusters, zones, etc. The local percentiles don't aggregate well and can be quite misleading in the aggregate.
* Bucketed counters. I'll update the docs in wiki so there is a better reference, but for now there are some details on how we use these in [this comment](https://github.com/Netflix/servo/issues/321#issuecomment-101115722). This is currently the preferred approach internally for most use-cases.

We are also experimenting with using [t-digests](https://github.com/Netflix/spectator/wiki/TDigest) for fairly accurate quantile approximation that still allows us to slice and dice effectively. However, they are much more expensive to work with so they can quickly become impractical for a lot of our use-cases right now.

**Comment by pparth** [comment]
The comment you mentioned actually describes our issue 100%. However, we go back to Servo for bucketed counters as i understand, and i really want us to stay to Spectator. Therefore, we will stay with locally computed percentiles, with the crappy Avg aggregate results, as you describe.

**Comment by brharrington** [comment]
Spectator has bucketed timers and counters, see for example:

https://github.com/Netflix/spectator/blob/master/spectator-ext-sandbox/src/main/java/com/netflix/spectator/sandbox/BucketTimer.java

I just need to get the docs updated to talk about the usage.

**Comment by pparth** [comment]
Oh, cool then!

**Comment by brharrington** [comment]
Simple example for self publishing:

https://github.com/Netflix-Skunkworks/iep-apps/tree/master/iep-atlas
