### ISSUE TITLE
Invalid tag value message on GC metrics

### ISSUE THREAD

**Issue by andysworkshop** [Netflix/spectator#300]
I'm using the `GcLogger` as directed in the documentation. I'm using version `0.38.1` of this library. My JVM is 1.8.0.51. G1 is enabled with `-XX:+UseG1GC`. Garbage collection metrics are reporting invalid tag value messages at `DEBUG` level in the logs.

    Invalid tag value Code Cache
    Invalid tag value Compressed Class Space
    Invalid tag value G1 Old Gen
    Invalid tag value G1 Survivor Space
    Invalid tag value G1 Eden Space

Each message is repeated 3 times.

Is this a bug or am I missing a registration step somewhere?

**Comment by brharrington** [comment]
I'm guessing the problem is the space. The servo registry has a mode to map unsupported characters to `_`. For the specific message, I'll have to dig a bit to figure out what is sending the error. I'm not a immediately seeing a match for that. Two follow up questions:

1. Is there a class name associated with the log messages you are seeing? That would help narrow down the source of the particular message.
2. Which registry are you binding to?

**Comment by andysworkshop** [comment]
Looks like the class is in the spring-cloud namespace. It's `o.s.c.n.m.atlas.AtlasMetricObserver`. The registry is `com.netflix.spectator.servo.ServoRegistry` which is injected by Spring.

**Comment by brharrington** [comment]
@jkschneider it looks like this is coming from the spring observer you wrote (see [spring cloud observer line 88](https://github.com/spring-cloud/spring-cloud-netflix/blob/master/spring-cloud-netflix-core/src/main/java/org/springframework/cloud/netflix/metrics/atlas/AtlasMetricObserver.java#L88)). The servo observer will transform disallowed characters to '_' (see [servo observer line 181](https://github.com/Netflix/servo/blob/master/servo-atlas/src/main/java/com/netflix/servo/publish/atlas/AtlasMetricObserver.java#L181)). Thoughts?

**Comment by jkschneider** [comment]
Thanks again for the report @andysworkshop. Your feedback has been super helpful.
