### ISSUE TITLE
Preventing garbage collection of gauge collection method

### ISSUE THREAD

**Issue by andysworkshop** [Netflix/spectator#301]
I don't want my gauge data collector (an `AtomicInteger`) to disappear at the whim of the garbage collector. Therefore I've taken to re-registering it immediately before the atomic integer is incremented. This doesn't feel right and the behaviour of duplicate registration like this is not clear to me. What's the correct way of registering a gauge collector on an `AtomicInteger` that won't disappear?

**Comment by brharrington** [comment]
Can you explain a bit more about how you are trying to use/update the value? It isn't clear to me how you would use the AtomicInteger if you aren't holding a reference to it. Typically, the usage is like:

```java
// Register
AtomicInteger value = registry.gauge("gaugeValue", new AtomicInteger());

// Then to update the gauge you use the reference to the Number
value.set(42);
```

The registry itself doesn't provide access to the number, it is basically just able to run a function on an object to get a current measurement for something. There are helpers for classes that implement `Number` because that is a common use-case we have run into.

So how do you plan to update the value if you don't have a reference to it?

**Comment by andysworkshop** [comment]
The AtomicInteger is a class member, for example:

protected AtomicInteger ai=new AtomicInteger(0);

Then later in the method that uses it:

    this.registry.gauge("theid",tagIterator,this.ai);

I know that my `ai` reference is safe. It was my understanding from the docs that the function accessor is weak and can go away. So when you say:

> it is basically just able to run a function on an object to get a current measurement for something

Is the function that you run here safe from garbage collection?

**Comment by brharrington** [comment]
I'll have to update the docs, looking at:

http://netflix.github.io/spectator/en/latest/intro/gauge/#using-number

I can see more ambiguity than needed. Consider this example:

```java
class Server {
  // Tracks the number of current connections to the server
  private AtomicInteger numConnections;

  public Server(Registry registry) {
    numConnections = registry.gauge("server.numConnections", new AtomicInteger(0));
  }

  public void onConnectionCreated() {
    numConnections.incrementAndGet();
    ...
  }

  public void onConnectionClosed() {
    numConnections.decrementAndGet();
    ...
  }

  ...
}
```

The registry will keep a weak reference to the AtomicInteger that was passed in. Since the server object has a strong reference it will only go away when the server goes way. Also note that it is only registered once at the beginning. Gauges are passive unlike counters/timers/distribution summaries. The registry will sample the value each polling interval to get the current state.

With the `Number` variants it will return the number that was passed in so you can do it as part of the assignment. That can also be split out if preferred:

```
class Server {
  // Tracks the number of current connections to the server
  private AtomicInteger numConnections;

  public Server(Registry registry) {
    numConnections = new AtomicInteger(0);
    registry.gauge("server.numConnections", numConnections);
  }

  ...
}
```

**Comment by andysworkshop** [comment]
That clarifies things a lot. You could pretty much copy and paste your post into the docs and it would do the trick.
