### ISSUE TITLE
Add an option to propagate errors to consumer of global registry when it has not been configured

### ISSUE THREAD

**Issue by twicksell** [Netflix/spectator#470]
An exception should be thrown when a user attempts to log metrics using the static global registry and no registries have been added. Currently there is no obvious user feedback to let them know they are missing this initialization. 

Because this is a change in behavior, it may be worth making this an opt-in behavior governed by a property.

**Comment by brharrington** [comment]
I was experimenting with this, but the main problem is that the static contexts where the global registry is used may be accessed before the proper initialization happens or after all the registries have been removed during shutdown. If it throws, then it breaks the app because of the initialization order not because there is a bug in initialization and nothing was added.

I thought about just logging something, but would need to figure out how to plumb it in. Right now the composite doesn't do any logging to avoid recursive cycles when used as part of logging appenders.

**Comment by brharrington** [comment]
I don't see a good option for supporting this right now. Closing, we can reopen if it becomes a bigger problem.
