### ISSUE TITLE
Java9 default method invocation fails when methods have parameters.

### ISSUE THREAD

**Issue by lviggiano** [Netflix/spectator#490]
Hi.

I am porting [one of my projects](https://github.com/lviggiano/owner/) to Java9 and I found [your code](https://github.com/Netflix/spectator/blob/993da1ca0dc9a822327a995ac414a5a39f2bfbee/spectator-api/src/main/java/com/netflix/spectator/impl/Config.java#L127) to solve the default method invocation on proxies:

```
MethodType rt = MethodType.methodType(method.getReturnType());
return MethodHandles.lookup()
    .findSpecial(declaringClass, method.getName(), rt, declaringClass)
    .bindTo(proxy)
    .invokeWithArguments(args);
```

my finding, is that this code only works when default methods have no parameters. When you have parameters on default method, you get a "method not found exception".

So I managed to find a fix for this:

```
MethodType rt = MethodType.methodType(method.getReturnType(), method.getParameterTypes());
return MethodHandles.lookup()
    .findSpecial(declaringClass, method.getName(), rt, declaringClass)
    .bindTo(proxy)
    .invokeWithArguments(args);
```

In this way, default methods are working also when they have arguments. My code is [slightly different](https://github.com/lviggiano/owner/blob/cba181cf426439f2c48b10ff76b783ecbe432d62/owner-java8/src/main/java/org/aeonbits/owner/util/Java8SupportImpl.java#L36), if you want to have a look.

Hope this could be helpful.

Best regards,
Luigi

**Comment by brharrington** [comment]
Thanks. Will take a look at your version when I get a chance.

**Comment by lviggiano** [comment]
@brharrington I noticed that in spectator api you have implemented a configuration framework similar to what I am doing with [OWNER](https://github.com/lviggiano/owner/).
I'll learn more from your code, maybe my project can offer some advantage to yours as well. Regards
Luigi.

**Comment by brharrington** [comment]
From skimming the docs, the OWNER library looks more comprehensive. I would have to read through it more carefully, but in many ways it looks similar to what you can do with [ProxyFactory in Archaius2](https://github.com/Netflix/archaius/blob/2.x/archaius2-core/src/test/java/com/netflix/archaius/ProxyFactoryTest.java). Though OWNER is much better documented, good job there.

The configuration stuff in the Spectator library is mostly just intended to provide a simple way to bind the Spectator library itself to a user configuration library. In the simplest case the user just needs to provide a function that maps a string key to a string value, e.g. `System::getProperty`.

At Netflix there are a number of configuration libraries that are widely used including [Archaius](https://github.com/Netflix/archaius/) and [Typesafe Config](https://github.com/lightbend/config).  For Spectator, we do not want to restrict or get in the way of the user's choice of configuration library. We have also found that quite often this choice is made because of other tooling. For example, teams using Akka or Spark often use Typesafe Config because that is the configuration library used by those projects. Similarly, using the default Netflix platform stack users would get Archaius. I would imagine it is relatively straightforward to use OWNER with Spectator.

Also for `spectator-api`, there is an explicit goal to have no dependencies other than `slf4j-api` (and there was considerable debate about that one). This can be a bit annoying at times because it can mean reinventing some wheels, but overall it has paid off in that we minimize problems for the users of the library. For the base libraries in our stack (logging, monitoring, configuration) there has always been a lot of debate as to which should be considered the lowest level.
