### ISSUE TITLE
GaugePoller - support error reporting when a thread is cancelled

### ISSUE THREAD

**Issue by rpalcolea** [Netflix/spectator#658]
Hi!

We use `PolledMeters` using `monitorValue`.

We were looking at an issue with our dashboards and thought we were losing metrics for specific polled meters and a potential issue with how we set them up.

One of the symptoms was that we were not trying to pull metrics for specific meters, like if they were lost. After some investigation, turns out that our code was throwing an exception.

We didn’t see any logging errors out of spectator with this which make us think that potentially the error happens inside thread created by the `GaugePoller` and when exception occurs, it’s getting cancelled only and we don’t get visibility of this (https://github.com/Netflix/spectator/blob/master/spectator-api/src/main/java/com/netflix/spectator/api/patterns/GaugePoller.java#L75)

Would it be nice/possible to add some logging around this or other ways to notify when a Gauge is in bad state?

**Comment by brharrington** [comment]
The exception is already logged, but you would need to enable trace level for `com.netflix.spectator`. In the past we have logged these at higher log levels, but would frequently get complaints from application owners that libraries they were forced to pull in via other platform components were causing lots of frivolous logs because they would be broken in some environments. We encourage the library owners to fix their code if we can, but more frequently we would see app owners just shut off logging for our libraries entirely. If you are interested in the gauge behavior, then enable the trace level for the spectator package. 

Example:

```java
public class PollingTest {

  @Test
  public void monitorValue() throws Exception {
    System.setProperty("org.slf4j.simpleLogger.defaultLogLevel", "trace");
    Registry registry = new DefaultRegistry();
    PolledMeter.using(registry)
        .withName("test")
        .monitorValue(this, PollingTest::getValue);
    PolledMeter.update(registry);
  }

  public int getValue() {
    throw new UnsupportedOperationException();
  }
}
```

Results in:

```
[main] TRACE com.netflix.spectator.api.patterns.PolledMeter - uncaught exception from gauge function for [test]
java.lang.UnsupportedOperationException
	at com.netflix.spectator.api.patterns.PollingTest.getValue(PollingTest.java:20)
	at com.netflix.spectator.api.patterns.PolledMeter$ValueState.update(PolledMeter.java:442)
	at com.netflix.spectator.api.patterns.PolledMeter$AbstractMeterState.doUpdate(PolledMeter.java:389)
	at com.netflix.spectator.api.patterns.PolledMeter.update(PolledMeter.java:110)
	at com.netflix.spectator.api.patterns.PollingTest.monitorValue(PollingTest.java:16)
```

**Comment by rpalcolea** [comment]
awesome, thanks for claryfing @brharrington
