### ISSUE TITLE
Using prometheus metrics

### ISSUE THREAD

**Issue by manan164** [Netflix/spectator#782]
Hi all,
We are using conductor and for instrumentation, we use Prometheus metrics. 
We see that all histogram metrics has percentile buckets like [mentioned](https://github.com/Netflix/spectator/blob/master/spectator-api/src/test/java/com/netflix/spectator/api/CompatibilityTest.java#L105)
Is there any way we can get p99 p90 directly from buckets. We are able to measure only average value using totalTime/count.

**Comment by manan164** [comment]
More detailed question, Is there a way we can [calculate](https://github.com/Netflix/spectator/blob/master/spectator-api/src/main/java/com/netflix/spectator/api/histogram/PercentileBuckets.java#L105) using Prometheus query without calling actual function.

**Comment by brharrington** [comment]
Ideally just map the data when reporting so it would look like a [Prometheus Histogram](https://prometheus.io/docs/concepts/metric_types/#histogram). Then you should be able to query it using the [histogram_quantile()](https://prometheus.io/docs/prometheus/latest/querying/functions/#histogram_quantile) function.

Since Spectator does not support Prometheus directly, I'm assuming you are using `spectator-reg-metrics3` or `spectator-reg-micrometer` and then using the appropriate bindings from one of those libraries. The best option is probably using `spectator-reg-micrometer` because it preserves dimensionality and has some hooks to transform the data. See the Micrometer docs for [Prometheus integration](https://micrometer.io/docs/registry/prometheus) for more details. In particular, you may need a filter that converts the `percentile` dimension intended for Atlas's [:percentiles operator](https://github.com/Netflix/atlas/wiki/math-percentiles) into the [Prometheus Histogram format](https://prometheus.io/docs/concepts/metric_types/#histogram).

If the filter is general enough and can be done with no dependencies other than `spectator-api` and `micrometer-core`, then we could probably include it with `spectator-reg-micrometer` for use when users choose to bind with Prometheus.
