### ISSUE TITLE
PolledMeter API is Underspecified

### ISSUE THREAD

**Issue by carl-mastrangelo** [Netflix/spectator#819]
When trying to make PolledMeter that checks a static function, I tried using `monitorValue(null, MyClass::myFunction)`.    I checked the docs about using null, but it does not describe what happens if a null value is passed.   It confusingly says:

> A weak reference will be kept to obj so that monitoring the object will not prevent garbage collection. The meter will go away when obj is collected. 

Since `null` is not ever garbage collected, this could reasonably interpreted as it will run forever.  I think either one of three things should happen:

1.  `null` is explicitly disallowed by checking it at the beginning of monitorValue, and the docs updated to recommend passing some other value.
2.  Preserve bug behavior, but log a warning before discarding the value.
3.  Use a special null-wrapping object, and let the meter run independent of object life time.

I appreciate the reason why this API exists (avoiding memory leaks), but really the api I wanted in the first place was `monitorValue(DoubleSupplier)`, which would have fit naturally with the function I need to call.

**Comment by brharrington** [comment]
> 1.  `null` is explicitly disallowed by checking it at the beginning of monitorValue, and the docs updated to recommend passing some other value.
> 2.  Preserve bug behavior, but log a warning before discarding the value.

Current behavior is not a bug, but I agree it can be confusing. As a general rule we try to avoid throwing by default for monitoring code because users often don't expect it (see [Testing - Exceptions](https://netflix.github.io/spectator/en/latest/intro/testing/#exceptions)). We'll update it to check for null with the normal behavior of logging a warning and only throwing if explicitly enabled.

 > I appreciate the reason why this API exists (avoiding memory leaks), but really the api I wanted in the first place was `monitorValue(DoubleSupplier)`, which would have fit naturally with the function I need to call.  

The reason we don't offer that is that users can easily use that method with something like `this::getSomeValue` and not realize it would prevent the object from ever getting collected. This was the source of a number of problems in the past. We're thinking of a compromise by adding another helper `monitorStaticMethodValue(DoubleSupplier)`. Hopefully the more explicit name will encourage correct usage.
