### ISSUE TITLE
Are there any plans to support publication of metrics to CloudWatch?

### ISSUE THREAD

**Issue by joshuapancho** [Netflix/spectator#856]
Hi,

The organisation I work for currently has a codebase that uses Servo to record request times to a downstream service, and leverages the [CloudWatchMetricObserver](https://github.com/Netflix/servo/blob/master/servo-aws/src/main/java/com/netflix/servo/publish/cloudwatch/CloudWatchMetricObserver.java) to publish these metrics to CloudWatch.

After looking through the wiki and playing around with Spectator, it seems that there is no equivalent polling/observer functionality to publish metrics to CloudWatch. Are there plans in the future to support this use case?

Thanks!

**Comment by brharrington** [comment]
There are no plans on our side to implement that functionality. At Netflix we only use CloudWatch for dynamic scaling with custom data. For those use-cases the clients just send into our internal systems and we can configure some data to go to CloudWatch if needed as part of that data flow. This is beneficial for us because it keeps our client simpler and allows us to do more complex aggregations (e.g. percentile approximations) across a cluster which is important for a few of our use-cases.

You could do it transitively by using `spectator-reg-micrometer` with the [micrometer](https://github.com/micrometer-metrics/micrometer/) integration for CloudWatch. If you are re-instrumenting and CloudWatch is the main use-case you could also probably just code to micrometer directly.

**Comment by joshuapancho** [comment]
Thanks for the thorough explanation and the recommendation!
